repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
        args: ['--maxkb=10000']
-   repo: https://github.com/pycqa/pylint
    rev: v2.12.2
    hooks:
    -   id: pylint
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black
    -   id: black-jupyter
# -   repo: https://github.com/pycqa/isort
#     rev: 5.10.1
#     hooks:
#     -   id: isort
#         name: isort (python)
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.2.2
    hooks:
    -   id: nbqa-black
    # -   id: nbqa-isort
